"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { FormField } from "@/components/ui/form-field";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import type {
  OutreachDraftRead,
  SenderSnapshotRead,
} from "@entities/outreach-draft";
import { buildRevisionPayload } from "./payload";
import { reviseOutreachDraftAction } from "./actions";

function signaturePreview(snapshot: SenderSnapshotRead | null): string[] {
  if (!snapshot) return [];
  const lines: string[] = [snapshot.senderName];
  if (snapshot.senderTitle) lines.push(snapshot.senderTitle);
  if (snapshot.companyName && snapshot.companyName !== snapshot.senderName) {
    lines.push(snapshot.companyName);
  }
  const whatsappNumber = snapshot.whatsappEnabled
    ? (snapshot.whatsappPhone ?? snapshot.phone)
    : null;
  if (whatsappNumber && whatsappNumber === snapshot.phone) {
    lines.push(`${whatsappNumber} · WhatsApp`);
  } else {
    if (snapshot.phone) lines.push(snapshot.phone);
    if (whatsappNumber) lines.push(`${whatsappNumber} · WhatsApp`);
  }
  if (snapshot.website) lines.push(snapshot.website);
  lines.push(snapshot.fromEmail);
  return lines;
}

/**
 * Compact human review/edit control for the current materialized draft. The user
 * edits only the subject and the canonical body; the plain-text and HTML bodies
 * are regenerated by the server as a new append-only version. No sending.
 */
export function OutreachDraftEditor({
  productId,
  opportunityId,
  leadId,
  draft,
}: {
  productId: string;
  opportunityId: string;
  leadId: string;
  draft: OutreachDraftRead;
}) {
  const router = useRouter();
  const [subject, setSubject] = useState(draft.subject ?? "");
  const [canonicalBody, setCanonicalBody] = useState(draft.canonicalBody ?? "");
  const [submitting, setSubmitting] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const preview = signaturePreview(draft.senderSnapshot);

  async function submit(event: React.FormEvent) {
    event.preventDefault();
    setSubmitting(true);
    setMessage(null);
    setError(null);
    try {
      const result = await reviseOutreachDraftAction(
        productId,
        opportunityId,
        leadId,
        draft.id,
        buildRevisionPayload({ subject, canonicalBody }),
      );
      if (result.ok) {
        setMessage(
          `Saved as v${result.draft?.version ?? "?"} — ready for review.`,
        );
        router.refresh();
      } else {
        setError(result.message ?? "The draft revision could not be saved.");
      }
    } catch {
      setError("The draft revision could not be saved.");
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <div className="rounded-lg border border-border p-4 text-sm">
      <div className="flex flex-wrap items-center gap-2">
        <span className="font-medium">Review &amp; edit current draft</span>
        <Badge tone="info">v{draft.version}</Badge>
        <Badge tone="success">Ready for review</Badge>
        <span className="text-xs text-muted-foreground">
          Saving creates a new version; previous versions are preserved.
        </span>
      </div>
      <p className="mt-1 text-xs text-muted-foreground">
        Edit the subject and the message body. The plain-text and HTML bodies are
        generated from the message body plus the structured signature — you never
        edit them separately.
      </p>

      <form onSubmit={submit} className="mt-3 space-y-3">
        <FormField label="Subject" htmlFor="outreach-subject">
          <Input
            id="outreach-subject"
            value={subject}
            onChange={(e) => setSubject(e.target.value)}
            autoComplete="off"
          />
        </FormField>
        <FormField
          label="Message body"
          htmlFor="outreach-canonical-body"
          hint="The closing and signature are added automatically; do not paste them here."
        >
          <Textarea
            id="outreach-canonical-body"
            rows={7}
            value={canonicalBody}
            onChange={(e) => setCanonicalBody(e.target.value)}
          />
        </FormField>

        <div className="rounded-md border border-border bg-muted/30 p-3">
          <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
            Generated signature (read-only)
          </p>
          <p className="mt-1 text-xs text-muted-foreground">
            Closing phrase and signature are generated from the structured sender
            profile and the message language.
          </p>
          {preview.length > 0 ? (
            <p className="mt-2 whitespace-pre-line font-mono text-xs text-foreground">
              {preview.join("\n")}
            </p>
          ) : (
            <p className="mt-2 text-xs text-destructive">
              No structured sender identity is attached to this draft.
            </p>
          )}
        </div>

        <div className="flex flex-wrap items-center gap-3">
          <Button type="submit" disabled={submitting} className="cursor-pointer">
            {submitting ? "Saving…" : "Save new version"}
          </Button>
          {message ? <span className="text-xs text-success">{message}</span> : null}
          {error ? (
            <span className="text-xs text-destructive">{error}</span>
          ) : null}
        </div>
      </form>
    </div>
  );
}
